# firstMsgDelay is the delay between when Bukkit is started and the first
# message is displayed. Delay is in 'ticks' == 1/20th of a second.
firstMsgDelay: 600

# nextMsgDelay is the delay between messages
nextMsgDelay: 1200

# msgOrder can be either Sequential or Random
#
# Sequential messages are displayed in the order they appear in the configuration file.
# Random messages are displayed in random order. This can be useful if you have a large number of tips.
msgOrder: Sequential

# msgList contains the messages to be displayed to all players.
#
# Text color is supported using the following color codes:
# %0 Black                    %8 Dark Gray
# %1 Dark Blue                %9 Blue
# %2 Dark Green               %A Green
# %3 Dark Aqua                %B Aqua
# %4 Dark Red                 %C Red
# %5 Dark Purple              %D Light Purple
# %6 Gold                     %E Yellow
# %7 Gray                     %F White

groupMsgEnabled: False

# If group messages are enabled above, then msgList is ignored. You must set a unique
# list of messages for each group that should see messages.
msgList:
    - "%ATip #1: %EThis server is running the %FTips %Eplug-in."
    - "%ATip #2: %FYour administrator should add Tips to make this more useful. :)"
    - "Tip #3: There is no third tip."

# Create lists of messages in this section. To enable a permissions group to see a set
# of messages, give that group a permission like tip.show.[groupname] like tip.show.Guest.
groupMsgList:
    Guest:
        - "%ATip #1: %EWelcome guest! We are glad to see you."
        - "%ATip #2: %EBe sure to visit the welcome base to get some basic supplies."
    Builder:
        - "%ATip #1: %EHello there Builder!"
        - "%ATip #2: %EYou can build in any open space."
    Admins:
        - "%ATip #1: %EHello Admin! Thanks for helping this server thrive."
        - "%ATip #2: %EUse the jail command to lock up troublemakers."
