# firstMsgDelay is the delay between when Bukkit is started and the first
# message is displayed. Delay is in 'ticks' == 1/20th of a second.
firstMsgDelay: 600

# nextMsgDelay is the delay between messages
nextMsgDelay: 1200

# msgOrder can be either Sequential or Random
#
# Sequential messages are displayed in the order they appear in the configuration file.
# Random messages are displayed in random order. This can be useful if you have a large number of tips.
msgOrder: Sequential

# msgList contains the messages to be displayed to all players.
#
# Text color is supported using the following color codes:
# %0 Black                    %8 Dark Gray
# %1 Dark Blue                %9 Blue
# %2 Dark Green               %A Green
# %3 Dark Aqua                %B Aqua
# %4 Dark Red                 %C Red
# %5 Dark Purple              %D Light Purple
# %6 Gold                     %E Yellow
# %7 Gray                     %F White

msgList:
    - "%ATip #1: %EThis server is running the %FTips %Eplug-in."
    - "%ATip #2: %FYour administrator should add Tips to make this more useful. :)"
    - "Tip #3: There is no third tip."

# msgListByGroup allows you to add additional tips that will only be displayed to members of that group
# These are in addition to the messages listed in msgList.
msgListByGroup:
    Guest:
        - "Hi Guest! Register on our forums at http://herpie.derpie"
        - "%FPlease remember to replant trees after you chop them %4completely%F!"
    Builder:
        - "You can use the %B/item%F command to give yourself building materials."


